backend = "glx";
experimental-backends = true;
vsync = true;

shadow = true;
shadow-radius = 16;
shadow-opacity = 0.4;
shadow-offset-x = -8;
shadow-offset-y = -8;

fading = true;
fade-in-step = 0.05;
fade-out-step = 0.05;
fade-delta = 6;

corner-radius = 14;
round-borders-on-cli = true;

inactive-dim = 0.05;
inactive-opacity = 0.97;
active-opacity = 1.0;

blur-background = true;
blur-background-frame = true;
blur-method = "dual_kawase";
blur-strength = 5;

wintypes = {
    tooltip = { opacity = 0.95; focus = true; shadow = true; };
    popup_menu = { opacity = 0.96; blur-background = true; };
    dropdown_menu = { opacity = 0.96; blur-background = true; };
    dock = { shadow = false; };
}