[General]
config_version=1
theme=frost

[panel0]
name=default
position=Bottom
panelSize=42
iconSize=24
length=80
percentLength=true
alignment=Center
plugins=mainmenu|taskbar|statusnotifier|volume|clock|configure