[General]
config_version=1
theme=frost

[panel0]
name=menubar
position=Top
panelSize=28
iconSize=20
length=100
percentLength=true
alignment=Center
plugins=mainmenu|taskbar|statusnotifier|clock|configure

[panel1]
name=dock
position=Bottom
panelSize=50
iconSize=36
length=60
percentLength=true
alignment=Center
plugins=taskbar