backend = "glx";
experimental-backends = true;
vsync = true;

shadow = true;
shadow-radius = 10;
shadow-opacity = 0.3;

fading = true;
fade-delta = 4;

corner-radius = 10;
round-borders-on-cli = true;

inactive-opacity = 0.97;
active-opacity = 1.0;

wintypes = {
    tooltip = { opacity = 0.95; focus = true; };
    dock = { shadow = false; };
}