backend = "glx";
experimental-backends = true;
vsync = true;
shadow = true;
shadow-radius = 18;
shadow-opacity = 0.35;
fading = true;
fade-delta = 4;
corner-radius = 10;
round-borders-on-cli = true;
inactive-opacity = 0.9;
active-opacity = 1.0;