[General]
config_version=1
theme=frost

[panel0]
name=main
position=Bottom
panelSize=40
iconSize=24
length=100
percentLength=true
alignment=Center
plugins=fancymenu|quicklaunch|taskbar|statusnotifier|tray|mount|volume|networkmonitor|worldclock|clock|cpuload|showdesktop|configure

[fancymenu]
type=fancymenu
alignment=Left
filterClear=true
autoSel=true
autoSelDelay=150

[quicklaunch]
type=quicklaunch
alignment=Left
apps\1\desktop=/usr/share/applications/pcmanfm-qt.desktop
apps\2\desktop=/usr/share/applications/qterminal.desktop
apps\3\desktop=/usr/share/applications/utn-os-installer.desktop
apps\size=3
[taskbar]
type=taskbar
closeOnMiddleClick=true
groupingEnabled=false

[statusnotifier]
type=statusnotifier
alignment=Right

[tray]
type=tray
alignment=Right

[mount]
type=mount
alignment=Right

[volume]
device=0
type=volume
alignment=Right

[networkmonitor]
type=networkmonitor
alignment=Right

[worldclock]
type=worldclock
alignment=Right

[clock]
type=clock
timeFormat=HH:mm
dateFormat=ddd MMM d
showTooltip=false
alignment=Right

[cpuload]
type=cpuload
alignment=Right

[showdesktop]
type=showdesktop
alignment=Right

[configure]
type=configure
alignment=Right
