backend = "glx";
experimental-backends = true;
vsync = true;

shadow = true;
shadow-radius = 5;
shadow-opacity = 0.25;
shadow-offset-x = -4;
shadow-offset-y = -4;

fading = true;
fade-delta = 5;

inactive-opacity = 1.0;
active-opacity = 1.0;

wintypes = {
    tooltip = { opacity = 0.95; focus = true; };
    popup_menu = { opacity = 0.97; };
    dropdown_menu = { opacity = 0.97; };
    dock = { shadow = false; };
}