[General]
config_version=1
theme=frost

[panel0]
name=default
position=Bottom
panelSize=40
iconSize=24
length=100
percentLength=true
alignment=Left
plugins=mainmenu|taskbar|statusnotifier|clock|configure